version: "3.3"

services:
  app:
    build:
      context: .
    restart: always
    environment:
      - ENV=prod
      - NODE_ENV=production
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "3000:3000"
